# Seed data for library_topics / library_readings — extracted from the
# frontend's former hardcoded LIBRARY_TOPICS array (Resources.jsx). Every
# entry links out to the publisher's own site; Safe Haven does not host or
# reproduce their material.
LIBRARY_TOPICS_SEED = [
    {
        "id": "alcohol",
        "label": "Alcohol Use",
        "icon": "Wine",
        "color": "text-amber-600",
        "bg": "bg-amber-50",
        "badge": "bg-amber-50 text-amber-700 border-amber-100",
        "blurb": "For anyone working on cutting back or quitting drinking.",
        "position": 0,
        "readings": [
            {
                "title": "Alcohol Use Disorder: Symptoms & Causes",
                "publisher": "Mayo Clinic",
                "format": "Guide",
                "desc": "A plain-language explanation of what alcohol use disorder is, how it develops, and the treatment approaches that are backed by research.",
                "url": "https://www.mayoclinic.org/diseases-conditions/alcohol-use-disorder/symptoms-causes/syc-20369243",
                "position": 0,
            },
            {
                "title": "Alcohol Fact Sheet",
                "publisher": "World Health Organization (WHO)",
                "format": "Fact sheet",
                "desc": "Global health data on alcohol's effects on the body and society, useful for understanding the bigger picture behind personal recovery.",
                "url": "https://www.who.int/news-room/fact-sheets/detail/alcohol",
                "position": 1,
            },
            {
                "title": "Alcoholics Anonymous (\"The Big Book\")",
                "publisher": "Alcoholics Anonymous World Services",
                "format": "Book",
                "desc": "The foundational 12-step recovery text, read by millions in AA fellowships worldwide, along with meeting-finder tools.",
                "url": "https://www.aa.org/the-big-book",
                "position": 2,
            },
            {
                "title": "NACADA National Helpline & Resources",
                "publisher": "NACADA (Kenya)",
                "format": "Directory",
                "desc": "Kenya's own national authority on alcohol and drug abuse, offering counseling referrals and public education resources.",
                "url": "https://nacada.go.ke",
                "position": 3,
            },
        ],
    },
    {
        "id": "drugs",
        "label": "Drugs & Substance Use",
        "icon": "Pill",
        "color": "text-cyan-600",
        "bg": "bg-cyan-50",
        "badge": "bg-cyan-50 text-cyan-700 border-cyan-100",
        "blurb": "Science-based facts on drug use, dependence, and treatment.",
        "position": 1,
        "readings": [
            {
                "title": "Drug Addiction (Substance Use Disorder): Symptoms & Causes",
                "publisher": "Mayo Clinic",
                "format": "Guide",
                "desc": "Explains what happens in the brain during addiction, why willpower alone often isn't enough, and what evidence-based treatment looks like.",
                "url": "https://www.mayoclinic.org/diseases-conditions/drug-addiction/symptoms-causes/syc-20365112",
                "position": 0,
            },
            {
                "title": "Drugs A–Z Reference Library",
                "publisher": "FRANK",
                "format": "Reference library",
                "desc": "An accessible, regularly updated reference on specific substances, their effects, and risks — written for the general public.",
                "url": "https://www.talktofrank.com/drugs-a-z",
                "position": 1,
            },
            {
                "title": "Opioid Overdose Fact Sheet",
                "publisher": "World Health Organization (WHO)",
                "format": "Fact sheet",
                "desc": "Life-saving information on recognizing an opioid overdose and how the antidote naloxone works — useful for people in recovery and their families alike.",
                "url": "https://www.who.int/news-room/fact-sheets/detail/opioid-overdose",
                "position": 2,
            },
            {
                "title": "Narcotics Anonymous",
                "publisher": "NA World Services",
                "format": "Fellowship & literature",
                "desc": "A 12-step fellowship and literature catalog for recovery from any drug, with meetings held worldwide.",
                "url": "https://www.na.org",
                "position": 3,
            },
        ],
    },
    {
        "id": "mental-health",
        "label": "Mental Health & Co-Occurring",
        "icon": "Brain",
        "color": "text-violet-600",
        "bg": "bg-violet-50",
        "badge": "bg-violet-50 text-violet-700 border-violet-100",
        "blurb": "For when addiction overlaps with anxiety, depression, or other conditions.",
        "position": 2,
        "readings": [
            {
                "title": "Depression: Symptoms & Causes",
                "publisher": "Mayo Clinic",
                "format": "Guide",
                "desc": "Covers symptoms, causes, and treatment options for depression, which commonly co-occurs with substance use.",
                "url": "https://www.mayoclinic.org/diseases-conditions/depression/symptoms-causes/syc-20356007",
                "position": 0,
            },
            {
                "title": "Understanding Mental Health Conditions",
                "publisher": "NAMI — National Alliance on Mental Illness",
                "format": "Guide & support directory",
                "desc": "Accessible explanations of common conditions plus peer support programs for people managing mental health and recovery together.",
                "url": "https://www.nami.org",
                "position": 1,
            },
            {
                "title": "Information & Support",
                "publisher": "Mind",
                "format": "Guide & directory",
                "desc": "A long-established mental health charity's plain-language guides on conditions, treatment options, and how to support someone else.",
                "url": "https://www.mind.org.uk",
                "position": 2,
            },
        ],
    },
    {
        "id": "relapse",
        "label": "Relapse Prevention & Coping Skills",
        "icon": "RefreshCcw",
        "color": "text-[#0D6E64]",
        "bg": "bg-teal-50",
        "badge": "bg-teal-50 text-teal-700 border-teal-100",
        "blurb": "Practical tools for staying steady through cravings and hard days.",
        "position": 3,
        "readings": [
            {
                "title": "Recovery Articles & Coping Tools",
                "publisher": "Hazelden Betty Ford Foundation",
                "format": "Article library",
                "desc": "A large, regularly updated library of practical articles on relapse prevention, triggers, and staying grounded in early recovery.",
                "url": "https://www.hazeldenbettyford.org/resources",
                "position": 0,
            },
            {
                "title": "SMART Recovery",
                "publisher": "SMART Recovery",
                "format": "Program & tools",
                "desc": "A secular, skills-based alternative or complement to 12-step programs, with self-management tools you can practice daily.",
                "url": "https://www.smartrecovery.org",
                "position": 1,
            },
            {
                "title": "Drug Addiction: Diagnosis & Treatment",
                "publisher": "Mayo Clinic",
                "format": "Guide",
                "desc": "Covers what makes relapse more likely and what evidence-based treatment and ongoing support look like for long-term recovery.",
                "url": "https://www.mayoclinic.org/diseases-conditions/drug-addiction/diagnosis-treatment/drc-20365113",
                "position": 2,
            },
        ],
    },
    {
        "id": "family",
        "label": "Family, Relationships & Codependency",
        "icon": "Users",
        "color": "text-[#8a2340]",
        "bg": "bg-rose-50",
        "badge": "bg-rose-50 text-rose-700 border-rose-100",
        "blurb": "Support for rebuilding trust and healthy relationships.",
        "position": 4,
        "readings": [
            {
                "title": "Al-Anon Family Groups",
                "publisher": "Al-Anon Family Groups",
                "format": "Fellowship & literature",
                "desc": "Support and literature for people affected by a loved one's drinking, including a meeting finder for families and friends.",
                "url": "https://al-anon.org",
                "position": 0,
            },
            {
                "title": "Family Support Resources",
                "publisher": "NAMI — National Alliance on Mental Illness",
                "format": "Guide",
                "desc": "Guidance for families navigating a loved one's mental health or co-occurring recovery journey, including how to set healthy boundaries.",
                "url": "https://www.nami.org",
                "position": 1,
            },
            {
                "title": "Books for Family & Loved Ones",
                "publisher": "Hazelden Betty Ford Foundation",
                "format": "Article & book library",
                "desc": "Articles and reading recommendations specifically written for partners, parents, and children of someone in recovery.",
                "url": "https://www.hazeldenbettyford.org/resources",
                "position": 2,
            },
        ],
    },
    {
        "id": "gambling",
        "label": "Gambling & Behavioral Addictions",
        "icon": "Dices",
        "color": "text-emerald-600",
        "bg": "bg-emerald-50",
        "badge": "bg-emerald-50 text-emerald-700 border-emerald-100",
        "blurb": "For compulsive gambling and other behavioral addictions.",
        "position": 5,
        "readings": [
            {
                "title": "National Council on Problem Gambling",
                "publisher": "NCPG",
                "format": "Directory & guide",
                "desc": "Education on problem gambling plus a confidential helpline and treatment/peer-support directory, including for affected family members.",
                "url": "https://www.ncpgambling.org",
                "position": 0,
            },
            {
                "title": "Peer Support Resources",
                "publisher": "NCPG",
                "format": "Directory",
                "desc": "An overview of Gamblers Anonymous, Gam-Anon, and SMART Recovery options for people struggling with gambling and their loved ones.",
                "url": "https://www.ncpgambling.org/help-treatment/peer-support-resources/",
                "position": 1,
            },
            {
                "title": "What Is Gambling Disorder?",
                "publisher": "American Psychiatric Association",
                "format": "Clinical overview",
                "desc": "A clinician-reviewed explanation of gambling disorder as a recognized behavioral addiction, including warning signs and treatment paths.",
                "url": "https://www.psychiatry.org/patients-families/gambling-disorder/what-is-gambling-disorder",
                "position": 2,
            },
        ],
    },
]