# Seed data for video_topics / videos — extracted from the frontend's
# former hardcoded VIDEO_LIBRARY array (Resources.jsx). Every entry links
# out to the original publisher/host; Safe Haven does not host or re-upload
# any footage.
VIDEO_TOPICS_SEED = [
    {
        "id": "understanding",
        "label": "Understanding Addiction",
        "icon": "Brain",
        "color": "text-violet-600",
        "bg": "bg-violet-50",
        "badge": "bg-violet-50 text-violet-700 border-violet-100",
        "blurb": "The science and psychology behind why addiction happens.",
        "position": 0,
        "videos": [
            {
                "title": "Everything You Think You Know About Addiction Is Wrong",
                "publisher": "Johann Hari · TED",
                "format": "Talk",
                "duration": "15 min",
                "desc": "A journalist's global search for what really drives addiction, built around the famous \"Rat Park\" experiment and the idea that connection — not willpower — is the antidote.",
                "url": "https://www.youtube.com/watch?v=PY9DcIMGxMs",
                "position": 0,
            },
            {
                "title": "The Power of Addiction and the Addiction of Power",
                "publisher": "Dr. Gabor Maté · TEDxRio+20",
                "format": "Talk",
                "duration": "19 min",
                "desc": "A physician who has spent decades treating severe addiction explains how early pain and trauma — not the substance itself — usually sit at the root.",
                "url": "https://www.youtube.com/watch?v=66cYcSak6nE",
                "position": 1,
            },
            {
                "title": "What Is Addiction?",
                "publisher": "National Institute on Drug Abuse (NIDA)",
                "format": "Explainer",
                "duration": "3 min",
                "desc": "A short, clear animation on what happens in the brain during addiction, from the U.S. government's lead research agency on drug use.",
                "url": "https://www.youtube.com/watch?v=FIdq9VveQMM",
                "position": 2,
            },
        ],
    },
    {
        "id": "stories",
        "label": "Real Recovery Stories",
        "icon": "Heart",
        "color": "text-[#8a2340]",
        "bg": "bg-rose-50",
        "badge": "bg-rose-50 text-rose-700 border-rose-100",
        "blurb": "First-hand accounts from people who've walked this road.",
        "position": 1,
        "videos": [
            {
                "title": "The Game Has Changed",
                "publisher": "Chris Herren · TEDxUMassAmherst",
                "format": "Talk",
                "duration": "17 min",
                "desc": "A former NBA player's honest account of addiction, rock bottom, and the long road back — now over 15 years into recovery.",
                "url": "https://www.youtube.com/watch?v=gAZ9aL30qOI",
                "position": 0,
            },
            {
                "title": "How Isolation Fuels Opioid Addiction",
                "publisher": "Dr. Rachel Wurzman · TED",
                "format": "Talk",
                "duration": "18 min",
                "desc": "A neuroscientist explains why loneliness is such a powerful driver of relapse — and why rebuilding community is one of the most protective things a person can do.",
                "url": "https://www.youtube.com/watch?v=pxEcvU0Vp_M",
                "position": 1,
            },
            {
                "title": "It Takes a Village to Recover From Drug Addiction",
                "publisher": "Charlotte Colman · TEDxGhent",
                "format": "Talk",
                "duration": "13 min",
                "desc": "A researcher challenges the \"once an addict, always an addict\" myth, showing how most people who use drugs do recover, gradually, with the right support around them.",
                "url": "https://www.youtube.com/watch?v=GKTbAZCF4e0",
                "position": 2,
            },
        ],
    },
    {
        "id": "skills",
        "label": "Coping Skills & Mindfulness",
        "icon": "Sparkles",
        "color": "text-[#0D6E64]",
        "bg": "bg-teal-50",
        "badge": "bg-teal-50 text-teal-700 border-teal-100",
        "blurb": "Practical tools for cravings, shame, and staying grounded.",
        "position": 2,
        "videos": [
            {
                "title": "A Simple Way to Break a Bad Habit",
                "publisher": "Dr. Judson Brewer · TED",
                "format": "Talk",
                "duration": "9 min",
                "desc": "A psychiatrist explains how getting curious about a craving — instead of fighting it — can loosen its grip, backed by his own mindfulness research.",
                "url": "https://www.youtube.com/watch?v=-moW9jvvMr4",
                "position": 0,
            },
            {
                "title": "The Power of Vulnerability",
                "publisher": "Brené Brown · TEDxHouston",
                "format": "Talk",
                "duration": "20 min",
                "desc": "One of the most-watched talks in the world, on shame, courage, and why letting yourself be seen is often the first step toward change.",
                "url": "https://www.youtube.com/watch?v=iCvmsMzlF7o",
                "position": 1,
            },
            {
                "title": "Free Guided Meditations",
                "publisher": "UCLA Mindful",
                "format": "Guided practice library",
                "duration": "5–30 min each",
                "desc": "A free library of studio-recorded guided meditations from UCLA's mindfulness center — useful for grounding, working with cravings, and settling before sleep.",
                "url": "https://www.uclahealth.org/uclamindful/guided-meditations",
                "position": 2,
            },
        ],
    },
    {
        "id": "family",
        "label": "For Family & Friends",
        "icon": "HeartHandshake",
        "color": "text-cyan-600",
        "bg": "bg-cyan-50",
        "badge": "bg-cyan-50 text-cyan-700 border-cyan-100",
        "blurb": "For the people who love someone in recovery.",
        "position": 3,
        "videos": [
            {
                "title": "Help and Hope for Families of Alcoholics",
                "publisher": "Al-Anon Family Group Headquarters",
                "format": "Explainer",
                "duration": "3 min",
                "desc": "A short, official introduction to Al-Anon's approach — recovery for the family, not just the person using — from the organization's own headquarters.",
                "url": "https://www.youtube.com/watch?v=FnhK4-vF55g",
                "position": 0,
            },
            {
                "title": "Recovering Together",
                "publisher": "Partnership to End Addiction",
                "format": "Video series",
                "duration": "Multiple short episodes",
                "desc": "Parents and family members who supported a loved one through substance use disorder share what helped, what didn't, and how they found hope.",
                "url": "https://www.youtube.com/playlist?list=PLu1Vzpklw-4NHPrs2DNF_SPoQV0i9HMPP",
                "position": 1,
            },
        ],
    },
    {
        "id": "kenya",
        "label": "Kenya & Swahili Voices",
        "icon": "MapPin",
        "color": "text-emerald-600",
        "bg": "bg-emerald-50",
        "badge": "bg-emerald-50 text-emerald-700 border-emerald-100",
        "blurb": "Local news features and first-hand stories, in English and Kiswahili.",
        "position": 4,
        "videos": [
            {
                "title": "Dada Aliyekuwa Mraibu wa Mihadarati Aeleza Safari ya Kuacha Uraibu",
                "publisher": "BBC News Swahili",
                "format": "Ushuhuda (Testimony)",
                "duration": "Habari fupi",
                "desc": "Kwa Kiswahili. Mwanamke kutoka Mombasa anasimulia safari yake kutoka kwenye uraibu wa dawa za kulevya hadi kupona, pamoja na maoni ya daktari wa akili kuhusu uraibu.",
                "url": "https://www.youtube.com/watch?v=sBskAfRtMzs",
                "position": 0,
            },
            {
                "title": "Waraibu wa Madawa ya Kulevya Wakabiliwa na Changamoto za Kujinasua",
                "publisher": "BBC News Swahili",
                "format": "Ripoti (Report)",
                "duration": "Habari fupi",
                "desc": "Kwa Kiswahili. Ripoti kutoka Mombasa kuhusu vijana wanaotaka kuachana na uraibu wa mihadarati na upungufu wa dawa ya methadone wanaokabiliana nao.",
                "url": "https://www.youtube.com/watch?v=B-JgYu4iRKk",
                "position": 1,
            },
            {
                "title": "Rehabilitation in Kenya: The Challenge of Addiction and Rehabilitation",
                "publisher": "KTN News Kenya",
                "format": "News feature",
                "duration": "Short feature",
                "desc": "In English. A look at what treatment and rehabilitation actually looks like in Kenya today, including the gaps people run into on the way to recovery.",
                "url": "https://www.youtube.com/watch?v=aeibLEGQND8",
                "position": 2,
            },
            {
                "title": "Battling Drug Addiction: Struggle for Sobriety Amid Govt. Tough Talk",
                "publisher": "NTV Kenya",
                "format": "Special report",
                "duration": "Short feature",
                "desc": "In English, with Kiswahili interviews. NTV's special report from Kenya's Coast region on the realities of addiction, poverty, and the search for sobriety.",
                "url": "https://ntvkenya.co.ke/newsfeatures/battling-drug-addiction-the-struggle-for-sobriety-amid-govt-tough-talk/",
                "position": 3,
            },
        ],
    },
]