"""add resources table

Revision ID: 3007bee5df25
Revises: 7e057dcae706
Create Date: 2026-07-18 20:25:11.354421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3007bee5df25'
down_revision = '7e057dcae706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_topics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('bg', sa.String(length=50), nullable=False),
    sa.Column('badge', sa.String(length=120), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_type'), ['type'], unique=False)

    op.create_table('video_topics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('bg', sa.String(length=50), nullable=False),
    sa.Column('badge', sa.String(length=120), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['library_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_readings_topic_id'), ['topic_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['video_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_topic_id'))

    op.drop_table('videos')
    with op.batch_alter_table('library_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_readings_topic_id'))

    op.drop_table('library_readings')
    op.drop_table('video_topics')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_type'))
        batch_op.drop_index(batch_op.f('ix_resources_region'))
        batch_op.drop_index(batch_op.f('ix_resources_county'))

    op.drop_table('resources')
    op.drop_table('library_topics')
    # ### end Alembic commands ###
