"""add crisis resource tables

Revision ID: 8ca715e01978
Revises: 71c16db49633
Create Date: 2026-07-23 14:15:18.060785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ca715e01978'
down_revision = '71c16db49633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crisis_categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('nav_label', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crisis_emergency_lines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('numbers', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crisis_hotlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('numbers', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['crisis_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crisis_hotlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crisis_hotlines_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crisis_hotlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crisis_hotlines_category_id'))

    op.drop_table('crisis_hotlines')
    op.drop_table('crisis_emergency_lines')
    op.drop_table('crisis_categories')
    # ### end Alembic commands ###
