"""add structured meeting schedule fields to groups

Revision ID: d3489078b325
Revises: 8ca715e01978
Create Date: 2026-07-23 15:32:04.834221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3489078b325'
down_revision = '8ca715e01978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_days_of_week', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('meeting_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('meeting_timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('meeting_timezone')
        batch_op.drop_column('meeting_time')
        batch_op.drop_column('meeting_days_of_week')

    # ### end Alembic commands ###
