"""add donations table

Revision ID: daec1263540e
Revises: d3489078b325
Create Date: 2026-07-25 16:21:49.195090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daec1263540e'
down_revision = 'd3489078b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=60), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=60), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=30), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_user_id'))
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_checkout_request_id'))

    op.drop_table('donations')
    # ### end Alembic commands ###
