"""add groups, group_memberships, group_messages tables

Revision ID: fd0ae5e61ead
Revises: 3007bee5df25
Create Date: 2026-07-21 13:30:33.184808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0ae5e61ead'
down_revision = '3007bee5df25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('meeting_schedule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_organizer_id'), ['organizer_id'], unique=False)

    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_memberships_group_user')
    )
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_memberships_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('group_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_author_id'))

    op.drop_table('group_messages')
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_memberships_group_id'))

    op.drop_table('group_memberships')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_groups_category'))

    op.drop_table('groups')
    # ### end Alembic commands ###
